### ISSUE TITLE
Categories for the software list?

### ISSUE THREAD

**Issue by kriswema** [ROCKNROLLKID/Open-Source-Community#3]
Maybe it would make the list a little easier to read if it had categories like "operating system", "image editing", "games", and so on.

**Comment by ROCKNROLLKID** [comment]
Another user suggested this, so I suppose I will do this one day. I will leave this open for a reminder. Thank you for your suggestion.

**Comment by ROCKNROLLKID** [comment]
Issue solved. Closing topic.
